auto        : false
lsi         : false
# permalink   : none
markdown    : kramdown
kramdown:
  input: GFM
sass:
    style: :compressed
paginate: 2
paginate_path: "page:num"
excerpt_separator:  '<!-- more -->'
