auto        : false
lsi         : false
# permalink   : none
markdown    : kramdown
kramdown:
  input: GFM
sass:
    style: :compressed
paginate: 5
paginate_path: "page:num"
# Gems

gems: [jekyll-paginate]
excerpt_separator:  ''
permalink: /:year/:month/:day/:title

